server:
  port: 9000
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.15.122:1521:XE
    username: system
    password: system

  data:
    mongodb:
      uri:  mongodb://127.0.0.1:27017/test?gssapiServiceName=mongodb&maxPoolSize=256


  thymeleaf:
    cache=false: false
    mode: LEGACYHTML5
